### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Rebornown** [BugenZhao/flashroute.rs#18]
The environment has been built，
The code works，
but it returns me:
IoError(Os {code: 2,kind:NotFound,message: "No such file or drectory" })
How can I do?What's wrong?

**Comment by Shi2uku** [comment]
What's your OS? Windows has not been totally tested yet. It is highly recommend that you run flashroute.rs on Linux.
Also, make sure you have Graphviz installed.

**Comment by Rebornown** [comment]
Thank you very much for your answer, I have tried to use windows, but when I compile, I will report an error, so I use Linux, the compilation is passed, but there is an error when I run the command,I think it's a picture path problem, right 发送自 Windows 10 版邮件应用 发件人: Shi2uku发送时间: 2021年1月27日 12:19收件人: BugenZhao/flashroute.rs抄送: Paul; Author主题: Re: [BugenZhao/flashroute.rs] Run Error (#18) What's your OS? Windows has not been totally tested yet. It is highly recommend that you run flashroute.rs on Linux.Also, make sure you have Graphviz installed.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Rebornown** [comment]
Thank you very much for your answer, 
I have tried to use windows, but when I compile, I will report an error, so I use Linux, the compilation is passed, but there is an error when I run the command,
I think it's a picture path problem, right?
The error report is as follows

1 / 1 [=======================================================] 100.00 % 43961.84/s [2021-01-27T06:39:53Z INFO  flashroute_rs::tracerouter] round  15: total        1, complete        0, remain        1;  sent       15, recv        0
1 / 1 [=======================================================] 100.00 % 50443.91/s [2021-01-27T06:39:53Z INFO  flashroute_rs::tracerouter] round  16: total        1, complete        0, remain        1;  sent       16, recv        1
1 / 1 [=======================================================] 100.00 % 57971.01/s [2021-01-27T06:39:53Z INFO  flashroute_rs::tracerouter] round  17: total        1, complete        1, remain        0;  sent       16, recv        1
[2021-01-27T06:39:53Z INFO  flashroute_rs::tracerouter] [Main] Waiting for 5 secs...
[2021-01-27T06:39:58Z INFO  flashroute_rs::tracerouter] Generating statistics and topology...
[2021-01-27T06:39:58Z INFO  flashroute_rs::network] [Main] receiving task stopped
[2021-01-27T06:39:58Z INFO  flashroute_rs::network] [Main] sending task stopped
[2021-01-27T06:39:58Z INFO  flashroute_rs::tracerouter] [Summary] Pre: sent 1, recv 0;  Main: sent 16, recv 1
[2021-01-27T06:39:58Z INFO  flashroute_rs::tracerouter] [Summary] Elapsed: 8 secs
[2021-01-27T06:39:58Z INFO  flashroute_rs::tracerouter] [Summary] Interfaces: forward 0, backward 1, total 1
[2021-01-27T06:39:58Z INFO  flashroute_rs::topo] [Summary] Total probed hosts: 2
[2021-01-27T06:39:58Z INFO  flashroute_rs::topo] Saving topology to fr.dot...
[2021-01-27T06:39:58Z INFO  flashroute_rs::topo] Plotting to fr.png...
Error: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

**Comment by Rebornown** [comment]
Thank you very much. I made a stupid mistake. I didn't install graphviz. When I installed it, it looked normal

**Comment by BugenZhao** [comment]
Yeah, the program will plot the generated dot topology by default. If it is not what you want, or the topology is too large to plot, you can transfer `—no-plot` or even `—no-dot` option to it.

**Comment by Rebornown** [comment]
Thank you very much.
